### ISSUE TITLE
adding splash effect to larger units

### ISSUE THREAD

**Issue by andy5995** [glest/glest-data#127]
This is the list that @KeithSammut and I worked on (did anyone else comment about it on Discord?). The list will need some fine-tuning and final review before the changes are implemented.

Romans:

- [x] Battering ram

 
 Greek:
 
- [x] Battering ram
 
- [x] Atlas (I'm not sure about this one)
 
 
 Magic:
 
 - [x] behemoth
 
 
 Persian:
 
- [x] Elephant
 

 Norsemen:
 
 - [x] Thor
 
 Indian:
     
Thunderbird air attack (I'm not sure about this one. Splash damage to another air unit would only damage that single unit more, not "splash" out to other units, as was the intent when I proposed this idea)

Elves:

- [x] Ent Melee Attack

Gryphon and Gryphon Rider Air Attack

**Comment by KeithSammut** [comment]
This has been added a year ago
