### ISSUE TITLE
Factions names are inconsistent

### ISSUE THREAD

**Issue by andy5995** [glest/glest-data#219]
The names of the factions are not consistent. Examples:

Egypt: is the name of a country

Persian: an adjective (relating to ancient Persia or modern Iran or its people or language.)

Romans: people of Rome

Greeks: people of Greece

The Great Ming: specifies a dynasty

Medieval: describes a time period (I'd suggest using the name that the creator gave it - Natulka)

Tech: ??? Who are the techs and when did they come from? Or is it a location, a time period ???

Indians: people of India... (Changing this to "Native Americans" wouldn't be correct either, plus it's rather long; I'd suggest choosing a specific tribe of North America, such as "Pawnee")

The reason that consistency is important is that consumers and end-users base their opinion of a product at least partially by appearance. I think @biels would agree xD

**Comment by mathusummut** [comment]
Indians can be rename to "Natives".

**Comment by andy5995** [comment]
Oh, I just typed this into Discord..

>But "natives" is too general so again not consistent with specific names such as "Romans", "Persians", etc. Natives can be native to anywhere :smiley:

In my opinion.

**Comment by JoaoMarcosCSilva** [comment]
We must agree on a single standard, and then follow it in order to name every faction.
Most of the time, when we use a faction name, we're saying "I'll play with the [faction name]", so perhaps we can change all names to the nationality.
So Egypt would become Egyptians, Persian become Persians, and so on.
The only problem would be to name Magic and Tech this way, but I'm sure it can be done.

**Comment by andy5995** [comment]
> So Egypt would become Egyptians, Persian become Persians, and so on.

That's what I was thinking too.

**Comment by andy5995** [comment]
>Medieval: describes a time period (I'd suggest using the name that the creator gave it - Natulka)

I renamed this today.

**Comment by mathusummut** [comment]
This is fixed.
