### ISSUE TITLE
add credits for main menu music

### ISSUE THREAD

**Issue by andy5995** [glest/glest-data#229]
Need to document the source and license of the main menu music

https://github.com/ZetaGlest/zetaglest-data/blob/develop/data/core/menu/

We can just start a CREDITS file in  zetaglest-data/data/core/ that also contains a link to the main credits file in https://github.com/ZetaGlest/zetaglest-data/blob/develop/docs/AUTHORS.data.txt

**Comment by KeithSammut** [comment]
as far as I know the music is royalty free
