### ISSUE TITLE
implementing traders, or a way to generate resources

### ISSUE THREAD

**Issue by andy5995** [glest/glest-data#29]
Some discussion about this on 

#27 

The problem with my "demo" method is that too many extra units need to be maintained and added.

A better way I think would be is if the trader could produce resources that could be harvested by workers. Maybe we'd call him an "alchemist" instead. "Convert 1000 wood to 100 gold".

We need more discussion about this before it gets implemented. Regardless of how it's done, I think the ability to harvest units should be added. I'll open a ticket in the source repo.

**Comment by andy5995** [comment]
I added a ticket to implement harvesting units ZetaGlest/zetaglest-source#35

**Comment by mathusummut** [comment]
With LUA, this is now easily possible.

**Comment by biels** [comment]
I can see some value in this, but I think it should be low priority. Currently the priority should be to consolidate the project IMHO. By this I mean taking it to at least the same level as MG where you can download binaries for all platofrms, has a good website, servers, etc. Maybe it's time to start separating things into milestones?

**Comment by KeithSammut** [comment]
I already wrote the lua script for the robber unit in the specialists, which takes gold on attacking buildings, but it's not working correctly, we need improvements in the way lua is used by the exe. Mathu shall be working on that as the next stage :P

**Comment by andy5995** [comment]
>Currently the priority should be to consolidate the project IMHO. By this I mean taking it to at least the same level as MG where you can download binaries for all platofrms, has a good website, servers, etc. Maybe it's time to start separating things into milestones?

Off-topic for this issue, @biels . But I did change the ticket to low-priority as you suggested.

**Comment by KeithSammut** [comment]
this has been settled

**Comment by ZeoxD** [comment]
> I already wrote the lua script for the robber unit in the specialists, which takes gold on attacking buildings, but it's not working correctly, we need improvements in the way lua is used by the exe. Mathu shall be working on that as the next stage :P

was there a problem in your script , or problem related to game itself.

**Comment by KeithSammut** [comment]
there are still problems with the robber, that's why I never published it
