### ISSUE TITLE
Specialists:buildings need multi-select set to "true"

### ISSUE THREAD

**Issue by andy5995** [glest/glest-data#90]
Multi-select needs to be set to true on buildings for the Specialists faction.

https://github.com/ZetaGlest/zetaglest-data/blob/535bf629ba18f1f8733f6ec54e75f5f514497a92/techs/zetapack/factions/specialists/units/battle_factory/battle_factory.xml#L12

And the uniform-select tag needs to be added, and set to true.

Example: https://github.com/ZetaGlest/zetaglest-data/blob/535bf629ba18f1f8733f6ec54e75f5f514497a92/techs/zetapack/factions/persian/units/elephant_cage/elephant_cage.xml#L14

**Comment by KeithSammut** [comment]
I already made these all to true, you must have deleted my commit

**Comment by andy5995** [comment]
Nothing shows in the commit history except for the addition of the faction

https://github.com/ZetaGlest/zetaglest-data/commits/develop/techs/zetapack/factions/specialists/units/battle_factory/battle_factory.xml
